spring:
  datasource:
    url: ${URL_DATABASE}
    username: ${USERNAME_DATABASE}
    password: ${PASSWORD_DATABASE}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
server:
  port: 8080
pagBank:
  api:
    url: ${URL_SANDBOX_PAGBANK}
    bearer_token: ${TOKEN_PAGBANK}