## Fazer um GET com o ID do Checkout, para buscar as informações do ckeckout

GET https://sandbox.api.pagseguro.com/checkouts/{checkout_id}
Authorization: Bearer {{PAGBANK_TOKEN}}
Content-Type: application/json
